emb: 384
seq: 1024
vocab: 64

defaults:
  - /stack@xformer.stack_configs:
     - encoder_local
     - encoder_random
     - decoder_nystrom_favor
  - _self_

xformer:
  _target_: xformers.factory.model_factory.xFormer
